version: 2.1
orbs:
  maven: circleci/maven@1.0
  sonarcloud: sonarsource/sonarcloud@1.0.3
build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan
workflows:
  maven_test:
    jobs:
      - maven/test
  main:
    jobs:
      - build:
          context: sonarcloud
